no_source()

library(massdatabase)
masstools::setwd_project()
rm(list = ls())

dir.create("data_analysis/massdatabase",
           showWarnings = FALSE,
           recursive = TRUE)

setwd("data_analysis/massdatabase/")

# "Request functions" is series functions that could be used to
# request one specific compound/pathway information using web crawler.

# BIGG model database

# [BIGG model](http://bigg.ucsd.edu/)is a knowledge base of
# genome-scale metabolic network reconstructions.

# Get the BIGG model information.

x <-
  request_bigg_model_info()

dim(x)
head(x)

# Get the BIGG universal metabolite information.

x <-
  request_bigg_universal_metabolite_info()

dim(x)
head(x)

# Get one specific metabolite information.
x <-
  request_bigg_universal_metabolite(metabolite_id = "g3p",
                                    return_form = "list")
names(x)
x$database_link
x
# Get universal reaction information.

x <-
  request_bigg_universal_reaction_info()
dim(x)
head(x)

# Get one specific reaction information.
x <-
  request_bigg_universal_reaction(reaction_id = "ADA",
                                  return_form = "list")
names(x)
x$reaction_string

# Get BIGG model version.

request_bigg_version()

# ChEBI database

# Chemical Entities of Biological Interest
# ([ChEBI](https://www.ebi.ac.uk/chebi/)) is a freely available
# dictionary of molecular entities focused on ‘small’ chemical compounds.

# Get one specific ChEBI compound information.
x <-
  request_chebi_compound(compound_id = "CHEBI:18358")
names(x)
x$base_info

# FooDB database

# [FooDB](https://foodb.ca/) is the world’s largest and
#  most comprehensive resource on food constituents, chemistry and biology.

# Get the FooDB compound information.
x <-
  request_foodb_compound_info()
dim(x)
head(x)

# Get one specific FooDB compound information.

x <-
  request_foodb_compound(compound_id = "FDB000004",
                         return_form = "list")
names(x)
x[1:5]

# Get one specific FooDB compound MS2 spectrum.

x <-
  request_foodb_compound_ms2(compound_id = "FDB000004")
names(x)
x$`142524`


# HMDB database

# The [Human Metabolome Database (HMDB)](https://hmdb.ca/)
# is a freely available electronic database containing detailed
# information about small molecule metabolites found in the human body.

# Get one specific HMDB compound information.
x <-
  request_hmdb_metabolite(metabolite_id = "HMDB0000001",
                          return_form = "list")
names(x)
head(x)

# KEGG database

# [KEGG](https://www.genome.jp/kegg/) is a database resource
#  for understanding high-level functions and utilities of the biological
#  system, such as the cell, the organism and the ecosystem, from molecular-level information, especially large-scale molecular datasets generated by genome sequencing and other high-throughput experimental technologies.

# Get all KEGG compound information.
x <-
  request_kegg_compound_info()
dim(x)
head(x)

# Get one specific KEGG compound information.
x <-
  request_kegg_compound("C02886", "list")
names(x)
x

# Get all KEGG drug information.
x <-
  request_kegg_drug_info()
dim(x)
head(x)

# Get one specific KEGG drug information.
x <-
  request_kegg_drug("D00001", "list")
names(x)
x

# Get all KEGG reaction class (rclass) information.
x <-
  request_kegg_rclass_info()
dim(x)
head(x)

# Get one specific KEGG reaction information.
x <-
  request_kegg_reaction(reaction_id = "R00001")
names(x)
x

# Get all pathway information.
x <-
  request_kegg_pathway_info(organism = "hsa")
dim(x)
head(x)

# Get one specific pathway information.
x <-
  request_kegg_pathway(pathway_id = "hsa00010")
names(x)
x

# LipidBank
# The official database of Japanese Conference on the
# Biochemistry of Lipids (JCBL). [Link](https://lipidbank.jp/)

# Get the LipidBank lipid class.
x <-
  request_lipidbank_lipid_class(lipid_class = "Wax")
dim(x)
head(x)

# LipidMaps
# [LIPID MAPS Lipidomics Gateway](https://www.lipidmaps.org/)
# was created in 2003 via an NIH “Glue Grant” to provide access
# to lipid nomenclature, databases, tools, protocols, standards, tutorials, meetings, publications, and other resources and serving the international lipid research community.

# Get one specific lipid information.
x <-
  request_lipidmaps_lipid(lipid_id = "LMFA01030001")
x

# WikiPedia

# We can also get information from WikiPedia.
# Get one specific compound information.
x <-
  request_wikipedia_compound(compound_id = "Microcystin-LR")
dim(x)
head(x)

# Get the classification of one species
x <-
  request_wikipedia_scientific_classification(species_id = "Aaptos ciliata")
dim(x)
x
