no_source()

library(massdatabase)
masstools::setwd_project()
rm(list = ls())

dir.create("data_analysis/massdatabase",
           showWarnings = FALSE,
           recursive = TRUE)

setwd("data_analysis/massdatabase/")

# "Download functions" is series functions that could be used to download online databases.

# BIGG model database

# [BIGG model](http://bigg.ucsd.edu/)is a knowledge base of
# genome-scale metabolic network reconstructions.

# Download the BIGG model data

download_bigg_model(model_id = "iND750")


# ChEBI database

# Chemical Entities of Biological Interest
# ([ChEBI](https://www.ebi.ac.uk/chebi/)) is a freely available dictionary
# of molecular entities focused on ‘small’ chemical compounds.
# Download ChEBI compound database

# download_chebi_compound(path = ".")

# FooDB database

# [FooDB](https://foodb.ca/) is the world’s largest and most
# comprehensive resource on food constituents, chemistry and biology.

# GNPS database

# The [GNPS](https://gnps-external.ucsd.edu/gnpslibrary)
# GNPS is a web-based mass spectrometry ecosystem that aims
# to be an open-access knowledge base for community-wide organization
# and sharing of raw, processed, or annotated fragmentation mass spectrometry
# data (MS/MS). GNPS aids in identification and discovery throughout
# the entire life cycle of data; from initial data acquisition/analysis to post publication.

# Download one GNPS compound database

download_gnps_spectral_library(gnps_library = "HMDB", 
                               path = "GNPS_HMDB")

# KEGG database

# [KEGG](https://www.genome.jp/kegg/) is a database resource for
# understanding high-level functions and utilities of the biological
#  system, such as the cell, the organism and the ecosystem,
#  from molecular-level information, especially large-scale molecular datasets generated by genome sequencing and other high-throughput experimental technologies.

# # Download KEGG compound database
# download_kegg_compound(path = "KEGG_compound")

# Download KEGG pathway database

# download_kegg_pathway(path = "KEGG_pathway", organism = "hsa")

# Download KEGG reaction class database
# download_kegg_rclass()
#
# Download KEGG drug database

# download_kegg_drug(path = ".")

# LipidBank
# The official database of Japanese Conference on the Biochemistry of Lipids (JCBL). 
# [Link](https: //lipidbank.jp / )
# Download the LipidBank lipid class database.

download_lipidbank_lipid_class(lipid_class = "Acylglycerol", path = ".")


# LipidMaps

# [LIPID MAPS Lipidomics Gateway](https: /  / www.lipidmaps.org / ) 
# was created in 2003 via an NIH “Glue Grant” to provide access to lipid
#  nomenclature, databases, tools, protocols, standards, tutorials, 
#  meetings, publications, and other resources and serving the 
#  international lipid research community.

# Download lipidmaps database
download_lipidmaps_lipid(path = ".")

# MassBank

# [MassBank](https: /  / massbank.eu / MassBank / ) 
# is a community effort and you are invited to contribute.
#  Please refer to our contributor documentation and get in touch via github or email.

# Download MassBnak compound database.
download_massbank_compound(source = "nist")

# SMPDB

# [SMPDB](https: /  / www.smpdb.ca / ) is an interactive, 
# visual database containing more than 30000 small molecule pathways found in humans only.

# Download SMPDB pathway database.
download_smpdb_pathway(path = ".")

